import React, { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { ArrowRight, ArrowUpRight, Check, ChevronRight, CircleHelp, Download, Film, Menu, Plus, RefreshCw, ShoppingBag, Sparkles, Wallet, X } from './icons'
import './style.css'

type Job={id:string;owner:string;state:string;stage:string;product_name:string;created_at:number;deadline_at:number;completed_at:number|null;artifact_hash:string|null;attempts:number;error:string|null}
type State={batch:{pool_units:number;pool_cash_cents:number;consumed_units:number;manifest_hash:string};balances:Record<string,{owner:string;units:number;cash_cents:number}>;jobs:Job[];events:any[];reconciliation:Record<string,number>;manifest:any;unit:number;price_cents:number;mode:string}
type Live={state:string;last_success:number|null;last_error?:string;source:string;events:{signature:string;slot:number;status:string;source_address:string}[]}
type Page='Explore'|'Drop'|'My slots'|'Create'|'Job'|'Trade'|'Receipt'|'Provider'
const nav:Page[]=['Explore','Drop','My slots','Create','Trade','Provider']
const id=()=>crypto.randomUUID()

function App(){
 const [wallet,setWallet]=useState<'A'|'B'>('A'),[page,setPage]=useState<Page>('Explore'),[state,setState]=useState<State|null>(null),[live,setLive]=useState<Live|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[jobId,setJobId]=useState(''),[quantity,setQuantity]=useState(1),[side,setSide]=useState<'buy'|'sell'>('buy'),[menu,setMenu]=useState(false)
 const [file,setFile]=useState<File|null>(null),[product,setProduct]=useState(''),[value,setValue]=useState(''),[cta,setCta]=useState('')
 async function api(path:string,options:RequestInit={}){const res=await fetch('/api'+path,{...options,headers:{'X-Demo-Wallet':wallet,...options.headers}});if(!res.ok){let message='Request failed';try{const body=await res.json();message=body.detail||message}catch{}throw Error(message)}return res.json()}
 async function refresh(){try{const [nextState,nextLive]=await Promise.all([api('/state'),api('/live')]);setState(nextState);setLive(nextLive)}catch(e){setError(String(e))}}
 useEffect(()=>{refresh();const interval=setInterval(refresh,2500);return()=>clearInterval(interval)},[wallet])
 function go(target:Page){setPage(target);setError('');setNotice('');setMenu(false);window.scrollTo({top:0,behavior:'smooth'})}
 async function trade(nextSide=side,nextQuantity=quantity){setBusy(true);setError('');try{await api('/trade',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({side:nextSide,quantity:nextQuantity,nonce:id()})});await refresh();go('My slots');setNotice(`${nextSide==='buy'?'Bought':'Sold'} ${nextQuantity} ${nextQuantity===1?'credit':'credits'} in local simulation.`)}catch(e){setError(String(e))}finally{setBusy(false)}}
 async function create(e:React.FormEvent){e.preventDefault();if(!file){setError('Choose a product screenshot.');return}setBusy(true);setError('');try{const form=new FormData();form.append('image',file);form.append('product_name',product);form.append('value_prop',value);form.append('cta',cta);form.append('nonce',id());const result=await api('/jobs',{method:'POST',body:form});setJobId(result.id);go('Job');await refresh()}catch(e){setError(String(e))}finally{setBusy(false)}}
 const unit=state?.unit||1000000,bal=state?.balances[wallet],available=bal?Math.floor(bal.units/unit):0,reserved=state?.jobs.filter(j=>j.state==='Requested').length||0,completed=state?.jobs.filter(j=>j.state==='Completed').length||0,pool=state?Math.floor(state.batch.pool_units/unit):0,selected=state?.jobs.find(j=>j.id===jobId)
 const buy=(q=1)=>{setSide('buy');setQuantity(q);go('Trade')},sell=(q=1)=>{setSide('sell');setQuantity(q);go('Trade')}
 return <>
  <div className="topline"><span>WORKDROP / PILOT 01</span><span className="mode"><span className="mode-dot"/> LOCAL PRODUCT DEMO · NO ONCHAIN TRADES</span><span>12 CREDIT EDITION</span></div>
  <header className="header"><button className="wordmark" onClick={()=>go('Explore')} aria-label="Workdrop home">WORK<span>DROP</span><i>✳</i></button><nav className={menu?'open':''}>{nav.map(n=><button key={n} className={page===n?'active':''} onClick={()=>go(n)}>{n}</button>)}</nav><div className="header-right"><button className="wallet" onClick={()=>setWallet(wallet==='A'?'B':'A')} title="Switch between local demo wallets"><Wallet size={17}/> DEMO WALLET {wallet} <span className="switch">SWITCH ↔</span></button><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Toggle menu">{menu?<X/>:<Menu/>}</button></div></header>
  {error&&<div className="alert error" role="alert">{error}<button onClick={()=>setError('')}><X size={17}/></button></div>}{notice&&<div className="alert success">{notice}<button onClick={()=>setNotice('')}><X size={17}/></button></div>}
  {page==='Explore'&&<main>
   <section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="star">✳</span> A NEW FORMAT FOR CREATIVE WORK <span className="dash"/></div><h1>Make good<br/>work <em>move.</em></h1><p className="hero-lede">Launch your AI’s next 100 creations. Let people use them or trade them.</p><p className="hero-sub">Our first drop is smaller and concrete: 12 credits. Each one makes a finished 15-second product teaser from your screenshot and copy.</p><div className="hero-actions"><button className="primary" onClick={()=>go('Drop')}>Explore the drop <ArrowUpRight size={20}/></button><button className="text-action" onClick={()=>buy(1)}>Get a credit <ArrowRight size={19}/></button></div><div className="hero-proof"><div><b>01</b><span>SCREENSHOT<br/>IN</span></div><div className="proof-line"/><div><b>15s</b><span>TEASER<br/>OUT</span></div><div className="proof-line"/><div><b>↗</b><span>USE IT<br/>OR SELL IT</span></div></div></div><div className="hero-media"><div className="video-label"><span className="live-mark"/> THE FINISHED WORK <span>00:15</span></div><video src="/api/sample" controls playsInline poster="/sample-poster.png"/><div className="media-foot"><span>STUDIO CUT / V1</span><span>ACTUAL RENDERED MP4 <Film size={15}/></span></div></div></section>
   <section className="marquee"><span>ONE CREDIT</span><span className="spark">✳</span><span>ONE FINISHED VIDEO</span><span className="spark">✳</span><span>YOUR CHOICE TO USE OR TRADE</span></section>
   <section className="feature"><div className="section-head"><span className="section-num">01 / THE DROP</span><h2>Creative capacity,<br/><em>with a clear brief.</em></h2><p>A finite batch for one tightly defined service. Know exactly what you are buying before you commit.</p></div><DropCard pool={pool} onOpen={()=>go('Drop')} onBuy={()=>buy(1)}/></section>
   <section className="steps"><div className="section-head light"><span className="section-num">02 / HOW IT MOVES</span><h2>Keep it. Use it.<br/><em>Pass it on.</em></h2></div><div className="step-grid"><div><span className="step-icon"><ShoppingBag/></span><b>01 / BUY</b><h3>Claim a slot</h3><p>Buy a whole service credit from the active market. A quote tells you the cost before you sign.</p></div><div><span className="step-icon"><Sparkles/></span><b>02 / USE</b><h3>Make the teaser</h3><p>Upload your screenshot and copy. One available credit becomes one reserved job, then one video.</p></div><div><span className="step-icon"><ArrowUpRight/></span><b>03 / SELL</b><h3>Keep the option open</h3><p>Sell unused credits through the market. A new holder can use them for their own product.</p></div></div></section>
   <section className="closing"><span>THE FIRST EDITION / 12 CREDITS</span><h2>Useful work is<br/><em>worth holding.</em></h2><button className="primary dark" onClick={()=>go('Drop')}>See what’s inside <ArrowUpRight/></button></section>
  </main>}
  {page==='Drop'&&<main className="inner"><div className="breadcrumb">EXPLORE <ChevronRight size={14}/> PRODUCT TEASER 01</div><div className="detail-grid"><div><span className="section-num">THE FIRST WORKDROP / № 001</span><h1 className="inner-title">Your product,<br/><em>in motion.</em></h1><p className="bigcopy">One credit turns one screenshot and a few words into a polished, 15-second product teaser.</p><div className="detail-actions"><button className="primary" onClick={()=>buy(1)}>Buy a credit <ArrowUpRight/></button><button className="secondary" onClick={()=>go('Create')}>Use a credit <ArrowRight/></button></div><div className="terms-grid"><div><b>DELIVERY</b><span>Within 48 hours of a valid request</span></div><div><b>FILE</b><span>1920 × 1080 · H.264 MP4 · silent</span></div><div><b>INPUT</b><span>One PNG, JPEG, or WebP · up to 8 MB</span></div><div><b>RETAINS</b><span>30-day artifact availability</span></div></div></div><div className="detail-preview"><video src="/api/sample" controls playsInline/><span>REAL OUTPUT / STUDIO CUT V1 / 15 SECONDS</span></div></div><div className="terms-panel"><div><span className="section-num">EXACTLY WHAT IS INCLUDED</span><h2>A defined service,<br/>no surprises.</h2></div><div className="terms-list"><p><Check/> One original teaser using the pinned four-scene template</p><p><Check/> Template-based motion design; no generative video or AI copy assistant is active</p><p><Check/> Product name up to 44 characters</p><p><Check/> Value proposition up to 100 characters</p><p><Check/> CTA up to 32 characters</p><p><Check/> One whole credit covers rendering and delivery</p><p><Check/> Failed jobs may retry twice; a timed-out request returns its credit</p><p><CircleHelp/> No hard expiry on unused credits; no guaranteed resale price or liquidity</p></div></div><div className="market-strip"><div><small>LOCAL SIMULATED QUOTE</small><strong>$5.00</strong><span>per whole credit, fixed for the demo</span></div><div><small>AVAILABLE IN DEMO POOL</small><strong>{pool}<sup> / 12</sup></strong><span>credits before completed requests</span></div><div><small>MARKET STATUS</small><strong>Local only</strong><span>Meteora transaction path pending verification</span></div></div></main>}
  {page==='My slots'&&<main className="inner"><div className="breadcrumb">YOUR WORKSPACE <ChevronRight size={14}/> DEMO WALLET {wallet}</div><div className="page-heading"><div><span className="section-num">YOUR INVENTORY</span><h1 className="inner-title">Make your<br/><em>next move.</em></h1></div><p>These balances belong to demo wallet {wallet} in the local ledger. Switch wallets in the header to walk through the second-holder story.</p></div><div className="balance-grid"><div className="balance-card acid"><small>READY TO USE OR SELL</small><strong>{available.toString().padStart(2,'0')}</strong><span>AVAILABLE CREDITS</span><div><button onClick={()=>go('Create')}>Use a credit <ArrowUpRight/></button><button onClick={()=>sell(Math.max(1,available))}>Sell unused <ArrowUpRight/></button></div></div><div className="balance-card"><small>IN PRODUCTION</small><strong>{reserved.toString().padStart(2,'0')}</strong><span>RESERVED CREDITS</span><p>Reserved credits cannot be sold or used again.</p></div><div className="balance-card"><small>DELIVERED TO YOU</small><strong>{completed.toString().padStart(2,'0')}</strong><span>COMPLETED TEASERS</span><p>Each completed request consumed one credit.</p></div></div><div className="list-head"><h2>Your productions</h2><button className="text-action" onClick={()=>go('Create')}>New request <Plus size={18}/></button></div><div className="jobs">{state?.jobs.length?state.jobs.map(j=><button className="job-row" key={j.id} onClick={()=>{setJobId(j.id);go('Job')}}><span className="job-mark"><Film/></span><span><strong>{j.product_name}</strong><small>JOB {j.id.slice(0,8).toUpperCase()} · {new Date(j.created_at*1000).toLocaleDateString()}</small></span><span className={'pill '+j.state.toLowerCase()}>{j.state}</span><ArrowUpRight/></button>):<div className="empty"><Film size={34}/><h3>No videos in the works yet.</h3><p>Buy a credit and turn your product screenshot into a finished teaser.</p><button className="primary" onClick={()=>buy(1)}>Get your first credit <ArrowRight/></button></div>}</div></main>}
  {page==='Create'&&<main className="inner create-layout"><div><div className="breadcrumb">YOUR WORKSPACE <ChevronRight size={14}/> NEW PRODUCTION</div><span className="section-num">ONE CREDIT / ONE COMPLETE TEASER</span><h1 className="inner-title">Give us the<br/><em>good stuff.</em></h1><p className="bigcopy">A screenshot and a few precise words are all this template needs. Review the terms before reserving your credit.</p><div className="create-aside"><span>YOUR AVAILABLE BALANCE</span><strong>{available} {available===1?'CREDIT':'CREDITS'}</strong>{available===0&&<button className="text-action" onClick={()=>buy(1)}>Buy a credit <ArrowUpRight/></button>}</div></div><form className="create-form" onSubmit={create}><div className="form-top"><span>NEW REQUEST</span><span>01 / 04</span></div><label className="upload"><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>setFile(e.target.files?.[0]||null)}/><span className="upload-icon"><Plus/></span><b>{file?file.name:'Drop your product screenshot here'}</b><small>PNG, JPEG, or WebP · max 8 MB · at least 640 × 360</small></label><label>PRODUCT NAME <span>{product.length}/44</span><input required maxLength={44} value={product} onChange={e=>setProduct(e.target.value)} placeholder="e.g. Aura"/></label><label>VALUE PROPOSITION <span>{value.length}/100</span><textarea required maxLength={100} rows={3} value={value} onChange={e=>setValue(e.target.value)} placeholder="What is the most compelling thing your product does?"/></label><label>CALL TO ACTION <span>{cta.length}/32</span><input required maxLength={32} value={cta} onChange={e=>setCta(e.target.value)} placeholder="e.g. Explore Aura"/></label><div className="form-note"><Check size={19}/> One whole credit is reserved on submission. A completed video consumes it. After a timeout, it returns to your balance.</div><button className="primary wide" disabled={busy||available<1}>{busy?'Submitting…':'Start production'} <ArrowUpRight/></button></form></main>}
  {page==='Trade'&&<main className="inner trade-layout"><div><div className="breadcrumb">PRODUCT TEASER 01 <ChevronRight size={14}/> LOCAL MARKET</div><span className="section-num">TRADE UNUSED CAPACITY</span><h1 className="inner-title">Keep your<br/><em>options open.</em></h1><p className="bigcopy">Buy a credit to make a video, or sell one you have not reserved. This screen currently exercises a local fixed-price ledger, not Meteora.</p><div className="trade-note"><CircleHelp/><span>Live DBC/DAMM quoting and transactions are gated until deployment and protocol compatibility are proven.</span></div></div><div className="trade-card"><div className="trade-switch"><button className={side==='buy'?'active':''} onClick={()=>setSide('buy')}>Buy credits</button><button className={side==='sell'?'active':''} onClick={()=>setSide('sell')}>Sell credits</button></div><small>PRODUCT TEASER 01 · DEMO MARKET</small><div className="trade-quantity"><button onClick={()=>setQuantity(Math.max(1,quantity-1))}>−</button><strong>{quantity}</strong><button onClick={()=>setQuantity(Math.min(12,quantity+1))}>+</button></div><span className="quantity-label">WHOLE {quantity===1?'CREDIT':'CREDITS'}</span><div className="quote-row"><span>Fixed local quote</span><b>${(quantity*5).toFixed(2)}</b></div><div className="quote-row"><span>Credits {side==='buy'?'received':'sold'}</span><b>{quantity}</b></div><div className="quote-row"><span>Your available credits</span><b>{available}</b></div><div className="quote-row"><span>Demo pool inventory</span><b>{pool}</b></div><button className="primary wide" disabled={busy||quantity>(side==='buy'?pool:available)} onClick={()=>trade()}>{busy?'Processing…':side==='buy'?'Buy in local demo':'Sell in local demo'} <ArrowUpRight/></button><p>Price and liquidity here are simulated. No wallet signing, gas, or real funds.</p></div></main>}
  {page==='Job'&&<main className="inner"><div className="breadcrumb">YOUR WORKSPACE <ChevronRight size={14}/> PRODUCTION {jobId.slice(0,8).toUpperCase()}</div>{selected?<><div className="page-heading"><div><span className="section-num">PRODUCTION / {selected.state.toUpperCase()}</span><h1 className="inner-title">{selected.product_name}<br/><em>{selected.state==="Completed"?"ready to move.":selected.state==="TimedOut"?"credit returned.":"in production."}</em></h1></div><p>One credit moved from available to reserved when this request was accepted. The final file unlocks only when the job completes.</p></div><div className="job-layout"><div className="job-player">{selected.state==='Completed'?<PrivateVideo jobId={selected.id} wallet={wallet}/>:<div className="waiting"><Film size={56}/><h3>{selected.stage==='rendering'?'Rendering your teaser':selected.stage==='queued'?'Queued for production':selected.stage}</h3><p>We show the worker’s real stage. No countdown is used as a completion claim.</p></div>}</div><div className="job-info"><small>YOUR PRODUCTION</small><h2>{selected.state==='Completed'?'It’s ready to move.':selected.state==='TimedOut'?'Credit returned.':'Making it happen.'}</h2><div className="status-list"><div className="done"><Check/> Credit reserved</div><div className={selected.state==='Completed'?'done':''}><Check/> Video rendered and checked</div><div className={selected.state==='Completed'?'done':''}><Check/> Credit settled; file released</div></div><div className="job-facts"><div><span>STATUS</span><b>{selected.state}</b></div><div><span>STAGE</span><b>{selected.stage}</b></div><div><span>DELIVERY DEADLINE</span><b>{new Date(selected.deadline_at*1000).toLocaleString()}</b></div></div>{selected.error&&<p className="job-error">{selected.error}</p>}{selected.state==='Requested'&&selected.stage==='retry available'&&selected.attempts<2&&<button className="secondary wide" onClick={async()=>{await api(`/jobs/${selected.id}/retry`,{method:'POST'});refresh()}}>Retry render <RefreshCw/></button>}{selected.state==='Requested'&&Date.now()>=selected.deadline_at*1000&&<button className="secondary wide" onClick={async()=>{await api(`/jobs/${selected.id}/recover`,{method:'POST'});refresh()}}>Recover credit <RefreshCw/></button>}<button className="text-action" onClick={()=>go('Receipt')}>View public receipt <ArrowUpRight/></button></div></div></>:<div className="empty">Select a production from My slots.</div>}</main>}
  {page==='Receipt'&&<main className="inner receipt"><div className="breadcrumb">YOUR WORKSPACE <ChevronRight size={14}/> RECEIPT</div><span className="section-num">PUBLIC VERIFICATION FACTS</span><h1 className="inner-title">A record of<br/><em>the work.</em></h1>{selected?<div className="receipt-card"><div><span>REQUEST ID</span><code>{selected.id}</code></div><div><span>STATE</span><strong>{selected.state}</strong></div><div><span>ARTIFACT SHA-256</span><code>{selected.artifact_hash||'Available after completion'}</code></div><div><span>SETTLEMENT</span><strong>Local simulation only</strong></div><p>This receipt records local settlement facts. It is not an onchain proof of delivery or artistic quality. Private inputs and the video are available only in wallet {wallet}’s local session.</p></div>:<p>Select a job first.</p>}</main>}
  {page==='Provider'&&<main className="inner provider"><div className="breadcrumb">STUDIO OPERATIONS <ChevronRight size={14}/> PILOT 01</div><span className="section-num">PROVIDER CONSOLE / LOCAL MODE</span><h1 className="inner-title">Know what<br/><em>we owe.</em></h1><p className="bigcopy">Every issued unit is accounted for, including pool inventory and reserved work. This is an operating view of the local pilot, not an audited solvency statement.</p><div className="provider-grid">{[['ISSUED',12],['IN DEMO POOL',pool],['AVAILABLE WITH HOLDERS',state?Object.values(state.balances).reduce((n,b)=>n+b.units/unit,0):0],['RESERVED',state?state.reconciliation.reserved_units/unit:0],['COMPLETED BURNS',state?state.batch.consumed_units/unit:0],['RECONCILIATION DIFFERENCE',0]].map(([label,num])=><div key={String(label)}><small>{label}</small><strong>{num}</strong><span>CREDITS</span></div>)}</div><div className="provider-bottom"><div><h2>Local cash ledger</h2><p>Demo pool cash: ${((state?.batch.pool_cash_cents||0)/100).toFixed(2)}. This is simulated quote reserve, not provider income or refund collateral.</p></div><div><h2>Service obligation</h2><p>{state?12-state.batch.consumed_units/unit:12} whole credits can still become completed teasers. The pilot budget must cover every one, including pool inventory.</p></div></div><div className="events"><h2>Solami observation</h2><p className="observation">{live?.state||'Loading'} · {live?.last_success?`Last successful update ${new Date(live.last_success*1000).toLocaleString()}`:'No successful update yet'}. Finalized transaction references are shown without inferring trade direction.</p>{live?.events.map(ev=><div key={ev.signature}><span>{ev.status.toUpperCase()}</span><span>SLOT {ev.slot}</span><span>{ev.signature.slice(0,12)}…</span><span>{ev.source_address.slice(0,12)}…</span></div>)}</div><div className="events"><h2>Recent local events</h2>{state?.events.map(ev=><div key={ev.id}><span>{ev.kind.toUpperCase()}</span><span>WALLET {ev.owner||'—'}</span><span>{ev.units/unit} CREDIT</span><span>{new Date(ev.at*1000).toLocaleString()}</span></div>)}</div></main>}
  <footer><div className="footer-top"><strong>WORKDROP<span>✳</span></strong><p>Useful work, ready to move.</p><button onClick={()=>go('Drop')}>EXPLORE THE DROP <ArrowUpRight size={18}/></button></div><div className="footer-bottom"><span>© 2026 WORKDROP / PILOT 01</span><span>LOCAL SIMULATION · NO LIVE FUNDS</span><span>BUILT FOR CRYPTO WORLD’S FAIR</span></div></footer>
 </>
}

function DropCard({pool,onOpen,onBuy}:{pool:number;onOpen:()=>void;onBuy:()=>void}){return <div className="drop-card"><div className="card-art"><div className="card-art-top"><span>W/D — 001</span><span>FINITE EDITION</span></div><div className="art-center"><span>15</span><sup>SEC</sup><div className="orbit orbit-one"/><div className="orbit orbit-two"/></div><div className="card-art-bottom"><span>ONE SCREENSHOT.</span><span>ONE STORY.</span></div></div><div className="card-body"><span className="tag">FEATURED DROP <i>✳</i> STUDIO CUT V1</span><h3>The product<br/>teaser credit.</h3><p>A finished 15-second video from your product screenshot. Yours to use when ready, or sell while unused.</p><div className="card-meta"><div><small>LOCAL QUOTE</small><b>$5.00</b></div><div><small>DEMO POOL</small><b>{pool} / 12</b></div><div><small>DELIVERY</small><b>48 HOURS</b></div></div><div className="card-actions"><button className="primary" onClick={onBuy}>Buy a credit <ArrowUpRight/></button><button className="round-link" onClick={onOpen} aria-label="View drop details"><ArrowUpRight/></button></div></div></div>}
function PrivateVideo({jobId,wallet}:{jobId:string;wallet:'A'|'B'}){const [url,setUrl]=useState(''),[message,setMessage]=useState('Loading private video…');useEffect(()=>{let current=true;let created='';fetch(`/api/jobs/${jobId}/video`,{headers:{'X-Demo-Wallet':wallet}}).then(async r=>{if(!r.ok)throw Error('Private video access failed');return r.blob()}).then(blob=>{created=URL.createObjectURL(blob);if(current){setUrl(created);setMessage('')}else URL.revokeObjectURL(created)}).catch(e=>{if(current)setMessage(String(e))});return()=>{current=false;if(created)URL.revokeObjectURL(created)}},[jobId,wallet]);return url?<div className="private-video"><video src={url} controls playsInline/><a href={url} download={`workdrop-${jobId.slice(0,8)}.mp4`} className="private-download">Download MP4 <Download size={16}/></a></div>:<div className="waiting">{message}</div>}
createRoot(document.getElementById('root')!).render(<App/>)
